apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: giropops
  name: girus
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    args: 
    - sleep 
    - "600"
    resources:
      limits:
        cpu: "2"
        memory: "512Mi"
      requests:
        cpu: "0.3"
        memory: "64Mi"

  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
