apiVersion: v1
kind: Pod
metadata:
  labels:
    run: meutestweb
  name: meutestweb
spec:
  containers:
  - image: nginx
    name: meutestweb
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
